# Generated by Django 5.2.5 on 2025-08-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('RUT', models.CharField(max_length=50)),
                ('DV', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=50)),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('paginas', models.CharField(max_length=50)),
                ('copias', models.CharField(max_length=50)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamos', models.CharField(max_length=50)),
                ('fecha_devolucion', models.CharField(max_length=50)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.lector')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primera_app.libro')),
            ],
        ),
    ]
