# Generated by Django 5.2.5 on 2025-09-10 20:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0002_biblioteca_lector_libro_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='DV',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='RUT',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamos',
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='autor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='nombre_biblioteca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='web',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='codigo_comuna',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombre_comuna',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='correo_lector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lector',
            name='digito_verificador',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.direccion'),
        ),
        migrations.AddField(
            model_name='lector',
            name='nombre_lector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='rut_lector',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='libro',
            name='fisico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='ubicacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nacionalidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_retorno',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.comuna'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='id_biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='copias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nacionalidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_lector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.lector'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.libro'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.categoria'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_tipo_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='primera_app.tipocategoria'),
        ),
    ]
